name: CI

on: 
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Run a one-line script
        run: echo "Hello, world! xyfei!"
        
      - name: Simulate an error
        env: 
          xname: ${{ toJSON(steps) }}
        run: echo $xname !!!

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: root
          TARGET: "/root/temp/githubaction"
          EXCLUDE: "/dist/, /node_modules/,/css/"
